### ISSUE TITLE
Make 1.0.1 release ?

### ISSUE THREAD

**Issue by marco-m** [aysylu/loom#103]
Hello,
it would be nice to have a 1.0.1 so that we could have a fix for https://github.com/aysylu/loom/issues/95 :-)

**Comment by marco-m** [comment]
@aysylu ?

**Comment by aysylu** [comment]
1.0.1 is now out on Clojars: https://clojars.org/aysylu/loom. Thanks for your patience!

**Comment by marco-m** [comment]
Thank you!
