### ISSUE TITLE
gen-rand throws exception for weighted graphs unless min-weight and max-weight are explicitly provided

### ISSUE THREAD

**Issue by tihancock** [aysylu/loom#51]
This is due to https://github.com/aysylu/loom/blob/master/src/loom/gen.clj#L15 where Random.nextInt is called with 0 if the default min-weight and max-weight are used.

I can see a few ways to avoid this exception:
1. A pre-condition asserting `(if (weighted? g) (< min-weight max-weight))`
2. Setting the default weights to some other sensible values (1 and 100?)
3. Changing rand-w to 
```#(if (< min-weight max-weight)
          (+ (.nextInt rnd (- max-weight min-weight)) min-weight)
          min-weight)```

Of the three I think I like some variation of the third best. I'm happy to put together a pull request if you think this is a good change.

**Comment by aysylu** [comment]
Thanks for catching this! I like the 1st option best because it makes it explicit what the preconditions are for the function to work correctly. I'd be happy to accept your PR if you're interested.
