### ISSUE TITLE
load graph from disk

### ISSUE THREAD

**Issue by colemanbroad** [aysylu/loom#88]
Can loom build a new graph from a .dot file? How should I save/load my graphs?

**Comment by aysylu** [comment]
You may choose to store your graphs in a file or a database of your choice, and then you'll want to specify how to port the graphs to Loom using Loom's API. Example: [Loom integration with Titanium](https://github.com/aysylu/titanium-loom). There's a way to export Loom graphs to graphviz, but not import them. Contributions that do this are welcome! It probably makes most sense to do this in a separate library.

**Comment by monora** [comment]
You may also have a look at my experiment with clojurewerkz.archimedes to store loom graphs as graphml files: https://github.com/monora/archimedes-loom/blob/master/src/archimedes_loom/core.clj
