### ISSUE TITLE
Graph Attribute

### ISSUE THREAD

**Issue by dcmcshan** [aysylu/loom#89]
Hi there.  Wondering how to set a graph attribute?  I have a weighted-digraph that I'd like rankdir = "LR", but I can't seem to figure it out.  Thanks!

**Comment by pataprogramming** [comment]
Hi, @dcmcshan. Assuming that you just want to set a graph attribute for GraphViz export, you can provide a free-form map of `:graph` options to the `loom.io` functions. For example:

```(loom.io/view g :graph {"rankdir" "LR"}```

or 

```(loom.io/view g :graph {:rankdir :LR}```

(Note that the `LR` is case-sensitive.)

I'm closing this issue as it looks like the above should solve your issue. If not, we can reopen.

I also have an experimental branch with graph attributes that are directly associated with the graphs (similar to how node and edge attributes are implemented). If this might be useful to anyone, please let me know.
